----CREATE TABLE SURVIVOR (
----    ID INT,
----    AGE INT,
----    GENDER VARCHAR(10),
----    AMMUNITION INT,
----    FOOD INT,
----    MEDICATION INT,
----    WATER INT,
----    IS_INFECTED BOOLEAN,
----    LATITUDE DECIMAL(10, 8),
----    LONGITUDE DECIMAL(10, 8),
----    NAME VARCHAR(50),
----    SUS_COUNTER INT,
----    PRIMARY KEY (ID)
----);
--

INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(3, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name1', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(14, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name2', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(4, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name3', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(5, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name4', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(6, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name5', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(7, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name6', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(8, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name7', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(9, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name8', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(10, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name9', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(11, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name10', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(12, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name11', 0);
INSERT INTO SURVIVOR(ID, AGE, GENDER, AMMUNITION, FOOD, MEDICATION, WATER, IS_INFECTED, LATITUDE, LONGITUDE, NAME, SUS_COUNTER) VALUES
(13, 23, 'Male', 10, 4, 6, 2, FALSE, 0.0, 0.0, 'name12', 0);